# permissions for end users to edit fcdinfoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fcdinfo-editor-role
rules:
- apiGroups:
  - topology.vkubeviewer.com
  resources:
  - fcdinfoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - topology.vkubeviewer.com
  resources:
  - fcdinfoes/status
  verbs:
  - get
