# permissions for end users to view vminfoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vminfo-viewer-role
rules:
- apiGroups:
  - topology.vkubeviewer.com
  resources:
  - vminfoes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - topology.vkubeviewer.com
  resources:
  - vminfoes/status
  verbs:
  - get
