# permissions for end users to edit vminfoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vminfo-editor-role
rules:
- apiGroups:
  - topology.vkubeviewer.com
  resources:
  - vminfoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - topology.vkubeviewer.com
  resources:
  - vminfoes/status
  verbs:
  - get
